image: ***REMOVED***:4567/***REMOVED***/automation/images/android-automation-docker:alpine
stages:
 - test
test:
  stage: test
  script: 
    - mkdir -p test/report
    - npm ci
  tags:
    - docker


